---
- name: Ensuring config directories of {{ install_daemon_name }} exist
  file:
    path: "{{ node_config_directory }}/{{ item.key }}"
    state: "directory"
    owner: "{{ config_owner_user }}"
    group: "{{ config_owner_group }}"
    mode: "0770"
  become: true
  with_dict: "{{ install_daemon }}"

- name: Copying over config.json files for {{ install_daemon_name }}
  template:
    src: "{{ item.key }}.json.j2"
    dest: "{{ node_config_directory }}/{{ item.key }}/config.json"
    mode: "0660"
  become: true
  register: ceph_config_jsons
  with_dict: "{{ install_daemon }}"
  notify: "{{ item.value.handlers | list }}"

- name: Copying over ceph.conf for {{ install_daemon_name }}
  vars:
    service_name: "{{ item.key }}"
  merge_configs:
    sources:
      - "{{ role_path }}/templates/ceph.conf.j2"
      - "{{ node_custom_config }}/ceph.conf"
      - "{{ node_custom_config }}/ceph/{{ inventory_hostname }}/ceph.conf"
    dest: "{{ node_config_directory }}/{{ item.key }}/ceph.conf"
    mode: "0660"
  become: true
  register: ceph_confs
  with_dict: "{{ install_daemon }}"
  notify: "{{ item.value.handlers | list }}"

- name: Checking {{ install_daemon_name }} containers
  become: true
  vars:
    container: "{{ ceph_containers[item.key] }}"
  kolla_docker:
    action: "compare_container"
    common_options: "{{ docker_common_options }}"
    name: "{{ container.name }}"
    image: "{{ container.image }}"
    volumes: "{{ container.volumes | reject('equalto', '') | list }}"
    environment: "{{ container.environment | default(omit) }}"
  register: check_ceph_containers
  when: item.key != "ceph-osd"
  with_dict: "{{ install_daemon }}"
  notify: "{{ item.value.handlers | list }}"

- name: Checking if {{ install_daemon_name }} container is running
  become: true
  kolla_docker:
    name: "{{ ceph_containers[item.key].name }}"
    action: "is_container_running"
  register: check_ceph_running
  when: item.key != "ceph-osd"
  with_dict: "{{ install_daemon }}"
  notify: "{{ item.value.handlers | list }}"
