---
- name: Initializing keyring list for {{ install_daemon_name }}
  set_fact:
    keyring_list: []
  run_once: True

- name: Loading the keyrings for {{ install_daemon_name }}
  set_fact:
    keyring_list: "{{ keyring_list | union([ceph_key_files[item]]) }}"
  with_items: "{{ ceph_containers[install_daemon_name].keyrings }}"
  run_once: True

- name: Pushing Ceph keyring for {{ install_daemon_name }}
  become: true
  bslurp:
    src: "{{ item.content }}"
    dest: "{{ node_config_directory }}/{{ install_daemon_name }}/{{ item.filename }}"
    sha1: "{{ item.sha1 }}"
    sha256: "{{ item.sha256 | default('') }}"
    mode: 0600
  with_items: "{{ keyring_list }}"
