---
- include_tasks: config.yml
  vars:
    install_daemon_name: "first ceph-mon"
    install_daemon:
      ceph-mon:
        handlers:
          - "Starting first ceph-mon container"

- name: Generating initial Ceph keyrings and monmap
  vars:
    bootstrap_mon: "{{ ceph_containers['ceph-mon'] }}"
  become: true
  kolla_docker:
    action: "start_container"
    common_options: "{{ docker_common_options }}"
    detach: False
    environment:
      KOLLA_BOOTSTRAP:
      KOLLA_CONFIG_STRATEGY: "{{ config_strategy }}"
      MON_IP: "{{ storage_interface_address }}"
      HOSTNAME: "{{ ceph_mon_hostname }}"
    image: "{{ bootstrap_mon.image }}"
    labels:
      BOOTSTRAP:
    name: "bootstrap_ceph_mon"
    restart_policy: no
    volumes: "{{ bootstrap_mon.volumes | reject('equalto', '') | list }}"
  notify:
    - Starting first ceph-mon container

- name: Setting host for cluster files
  set_fact:
    bootstrap_host: "{{ inventory_hostname }}"

- name: Flush handlers
  meta: flush_handlers
