---
- name: Create ceph mds pools
  kolla_ceph_pools:
    pool_name: "{{ item.pool_name }}"
    pool_type: "{{ item.pool_type }}"
    pool_pg_num: "{{ item.pool_pg_num }}"
    pool_pgp_num: "{{ item.pool_pgp_num }}"
    pool_application: "{{ item.pool_application }}"
    pool_erasure_name: "{{ item.pool_erasure_name | default('') }}"
    pool_erasure_profile: "{{ item.pool_erasure_profile | default('') }}"
    pool_rule_name: "{{ item.pool_rule_name | default('') }}"
    pool_rule: "{{ item.pool_rule | default('') }}"
    pool_cache_enable: "{{ item.pool_cache_enable | default('false') | bool }}"
    pool_cache_mode: "{{ item.pool_cache_mode | default('') }}"
    pool_cache_rule_name: "{{ item.pool_cache_rule_name | default('') }}"
    pool_cache_rule: "{{ item.pool_cache_rule | default('') }}"
    pool_cache_pg_num: "{{ item.pool_cache_pg_num | default('') }}"
    pool_cache_pgp_num: "{{ item.pool_cache_pgp_num | default('') }}"
  with_items: "{{ cephfs_pools }}"
  run_once: True
  delegate_to: "{{ available_mon }}"

- name: Geting ceph mds keyring
  become: true
  kolla_ceph_keyring:
    name: "mds.{{ ceph_mds_hostname }}"
    caps: "{{ ceph_client_mds_keyring_caps }}"
  register: ceph_mds_auth
  delegate_to: "{{ available_mon }}"

- name: Pushing ceph mds keyring to ceph-mds
  become: true
  copy:
    content: |
      [mds.{{ ceph_mds_hostname }}]
          key = {{ ceph_mds_auth.keyring.key }}
    dest: "{{ node_config_directory }}/ceph-mds/ceph.mds.{{ ceph_mds_hostname }}.keyring"
    mode: "0600"
