---
# mgr
- name: Enable ceph dashboard
  command: docker exec ceph_mon ceph mgr module enable dashboard --force
  changed_when: false
  run_once: true
  delegate_to: "{{ available_mon }}"
  when:
    - "'ceph-mgr' in ceph_install_daemons"
    - enable_ceph_dashboard | bool

- name: Enable the ceph mgr prometheus module
  command: docker exec ceph_mon ceph mgr module enable prometheus
  changed_when: false
  run_once: true
  delegate_to: "{{ available_mon }}"
  when:
    - "'ceph-mgr' in ceph_install_daemons"
    - enable_prometheus_ceph_mgr_exporter | bool

# mds
- name: Checking whether cephfs is created
  become: true
  command: docker exec ceph_mon ceph fs get cephfs
  register: cephfs_stat
  delegate_to: "{{ available_mon }}"
  failed_when: false
  changed_when: false
  run_once: true
  when:
    - "'ceph-mds' in ceph_install_daemons"
    - enable_ceph_mds | bool

- name: Creating ceph new filesystem
  become: true
  command: docker exec ceph_mon ceph fs new cephfs cephfs_metadata cephfs_data
  run_once: true
  delegate_to: "{{ available_mon }}"
  when:
    - "'ceph-mds' in ceph_install_daemons"
    - enable_ceph_mds | bool
    - cephfs_stat.rc != 0

