---
- name: Run command "ceph osd unset noout && ceph osd unset norebalance"
  become: true
  shell: docker exec ceph_mon ceph osd unset noout && docker exec ceph_mon ceph osd unset norebalance
  delegate_to: "{{ available_mon }}"
  changed_when: False
  when: ceph_action == "upgrade"

- include_tasks: check_ceph_health.yml
  when:
    - ceph_action == "upgrade"
    - enable_upgrade_health_check | bool

- name: Run command "ceph osd set noout && ceph osd set norebalance"
  become: true
  shell: docker exec ceph_mon ceph osd set noout && docker exec ceph_mon ceph osd set norebalance
  delegate_to: "{{ available_mon }}"
  changed_when: False
  when: ceph_action == "upgrade"

- name: Starting ceph-osd-{{ osd_disk.osd_data_id }} container for LVM mode
  become: true
  kolla_docker:
    action: "start_container"
    common_options: "{{ docker_common_options }}"
    environment:
      OSD_START: ""
      KOLLA_CONFIG_STRATEGY: "{{ config_strategy }}"
      OSD_ID: "{{ osd_disk.osd_data_id }}"
      OSD_STORE_TYPE: "{{ osd_disk.osd_store_type }}"
      OSD_DISK_MODE: "{{ osd_disk.osd_disk_mode }}"
      OSD_BLOCK: "{{ osd_disk.osd_data_block }}"
      OSD_WAL: "{{ osd_disk.osd_data_wal | default('') }}"
      OSD_DB: "{{ osd_disk.osd_data_db | default('') }}"
      TCMALLOC_MAX_TOTAL_THREAD_CACHE_BYTES: "{{ ceph_tcmalloc_tc_bytes }}"
    image: "{{ ceph_osd_image_full }}"
    name: "ceph_osd_{{ osd_disk.osd_data_id }}"
    pid_mode: "host"
    privileged: True
    volumes:
      - "{{ node_config_directory }}/ceph-osd/:{{ container_config_directory }}/:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "/dev/:/dev/"
      - "/run/:/run/:shared"
      - "/var/lib/ceph/osd/{{ osd_disk['osd_fs_uuid'] }}:/var/lib/ceph/osd/ceph-{{ osd_disk.osd_data_id }}"
      - "kolla_ceph_logs:/var/log/kolla-ceph/"

- name: Run command "ceph osd unset noout && ceph osd unset norebalance"
  become: true
  shell: docker exec ceph_mon ceph osd unset noout && docker exec ceph_mon ceph osd unset norebalance
  delegate_to: "{{ available_mon }}"
  changed_when: False
  when: ceph_action == "upgrade"

- name: Set the device class to osd {{ osd_disk.osd_data_id }}
  kolla_ceph_device_class:
    osd_id: "{{ osd_disk.osd_data_id }}"
    device_class: "{{ device_class }}"
  delegate_to: "{{ available_mon }}"
  when: device_class is defined