---
- name: Run command "ceph osd unset noout && ceph osd unset norebalance"
  become: true
  shell: docker exec ceph_mon ceph osd unset noout && docker exec ceph_mon ceph osd unset norebalance
  delegate_to: "{{ available_mon }}"
  changed_when: False
  when: ceph_action == "upgrade"

- include_tasks: check_ceph_health.yml
  when:
    - ceph_action == "upgrade"
    - enable_upgrade_health_check | bool

- name: Run command "ceph osd set noout && ceph osd set norebalance"
  become: true
  shell: docker exec ceph_mon ceph osd set noout && docker exec ceph_mon ceph osd set norebalance
  delegate_to: "{{ available_mon }}"
  changed_when: False
  when: ceph_action == "upgrade"

- name: Starting ceph-osd-{{ osd_id.stdout }} container
  become: true
  kolla_docker:
    action: "start_container"
    common_options: "{{ docker_common_options }}"
    environment:
      KOLLA_CONFIG_STRATEGY: "{{ config_strategy }}"
      OSD_ID: "{{ osd_id.stdout }}"
      JOURNAL_PARTITION: "{{ osd_disk.journal }}"
      TCMALLOC_MAX_TOTAL_THREAD_CACHE_BYTES: "{{ ceph_tcmalloc_tc_bytes }}"
      OSD_STORETYPE: "{{ ceph_osd_store_type }}"
      OSD_BS_FSUUID: "{{ osd_disk['fs_uuid'] }}"
    image: "{{ ceph_osd_image_full }}"
    name: "ceph_osd_{{ osd_id.stdout }}"
    pid_mode: "host"
    privileged: True
    volumes:
      - "{{ node_config_directory }}/ceph-osd/:{{ container_config_directory }}/:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "/dev/:/dev/"
      - "/var/lib/ceph/osd/{{ osd_disk['fs_uuid'] }}:/var/lib/ceph/osd/ceph-{{ osd_id.stdout }}"
      - "kolla_ceph_logs:/var/log/kolla-ceph/"

- name: Run command "ceph osd unset noout && ceph osd unset norebalance"
  become: true
  shell: docker exec ceph_mon ceph osd unset noout && docker exec ceph_mon ceph osd unset norebalance
  delegate_to: "{{ available_mon }}"
  changed_when: False
  when: ceph_action == "upgrade"

- name: Set the device class to osd
  kolla_ceph_device_class:
    osd_id: "{{ osd_id.stdout }}"
    device_class: "{{ device_class }}"
  delegate_to: "{{ available_mon }}"
  when: device_class is defined