---
# TODO(SamYaple): Improve failed_when and changed_when tests if possible
- name: Creating ceph erasure profile
  become: true
  command: docker exec ceph_mon ceph osd erasure-code-profile set {{ pool_erasure_name }} {{ pool_erasure_profile }}
  delegate_to: "{{ available_mon }}"
  changed_when: False
  run_once: True
  when: pool_type == "erasure"

- name: Creating ceph ruleset
  become: true
  command: docker exec ceph_mon ceph osd crush rule create-replicated {{ pool_rule_name }} {{ pool_rule }}
  delegate_to: "{{ available_mon }}"
  changed_when: False
  run_once: True
  when: pool_type == "replicated"

- name: Creating ceph erasure pool
  become: true
  command: docker exec ceph_mon ceph osd pool create {{ pool_name }} {{ pool_pg_num }} {{ pool_pgp_num }} {{ pool_type }} {{ pool_erasure_name }}
  delegate_to: "{{ available_mon }}"
  changed_when: False
  run_once: True
  when: pool_type == "erasure"

- name: Creating ceph replicated pool
  become: true
  command: docker exec ceph_mon ceph osd pool create {{ pool_name }} {{ pool_pg_num }} {{ pool_pgp_num }} {{ pool_type }} {{ pool_rule_name }}
  delegate_to: "{{ available_mon }}"
  changed_when: False
  run_once: True
  when: pool_type == "replicated"

- name: enable application for ceph pool
  become: true
  command: docker exec ceph_mon ceph osd pool application enable {{ pool_name }} {{ pool_application }}
  changed_when: False
  delegate_to: "{{ available_mon }}"
  run_once: True

- name: enable overwrites for ceph erasure pool
  become: true
  command: docker exec ceph_mon ceph osd pool set {{ pool_name }} allow_ec_overwrites true
  delegate_to: "{{ available_mon }}"
  changed_when: False
  run_once: True
  when: pool_type == "erasure"

- name: Creating ceph ruleset for cache
  become: true
  command: docker exec ceph_mon ceph osd crush rule create-replicated {{ pool_cache_rule_name }} {{ pool_cache_rule }}
  delegate_to: "{{ available_mon }}"
  changed_when: False
  run_once: True
  when: pool_cache_enable | bool

- name: Creating ceph pool for cache
  become: true
  command: docker exec ceph_mon ceph osd pool create {{ pool_name }}-cache {{ pool_cache_pg_num }} {{ pool_cache_pgp_num }} replicated {{ pool_cache_rule_name }}
  delegate_to: "{{ available_mon }}"
  changed_when: False
  run_once: True
  when: pool_cache_enable | bool

- name: Adding cache to pool
  become: true
  command: docker exec ceph_mon ceph osd tier add {{ pool_name }} {{ pool_name }}-cache
  delegate_to: "{{ available_mon }}"
  changed_when: False
  run_once: True
  when: pool_cache_enable | bool

- name: Setting cache-mode
  become: true
  command: docker exec ceph_mon ceph osd tier cache-mode {{ pool_name }}-cache {{ pool_cache_mode }}
  delegate_to: "{{ available_mon }}"
  changed_when: False
  run_once: True
  when: pool_cache_enable | bool

- name: Setting cache overlay for pool
  become: true
  command: docker exec ceph_mon ceph osd tier set-overlay {{ pool_name }} {{ pool_name }}-cache
  delegate_to: "{{ available_mon }}"
  changed_when: False
  run_once: True
  when: pool_cache_enable | bool

- name: Setting cache hit_set_type
  become: true
  command: docker exec ceph_mon ceph osd pool set {{ pool_name }}-cache hit_set_type bloom
  delegate_to: "{{ available_mon }}"
  changed_when: False
  run_once: True
  when: pool_cache_enable | bool

- name: Setting cache target_max_bytes
  become: true
  command: docker exec ceph_mon ceph osd pool set {{ pool_name }}-cache target_max_bytes {{ ceph_target_max_bytes }}
  delegate_to: "{{ available_mon }}"
  changed_when: False
  run_once: True
  when:
    - pool_cache_enable | bool
    - ceph_target_max_bytes != ''

- name: Setting cache target_max_objects
  become: true
  command: docker exec ceph_mon ceph osd pool set {{ pool_name }}-cache target_max_objects {{ ceph_target_max_objects }}
  delegate_to: "{{ available_mon }}"
  changed_when: False
  run_once: True
  when:
    - pool_cache_enable | bool
    - ceph_target_max_objects != ''
